language: node_js
node_js:
 - "8"
 - "10"
 - "node"
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn run lint
  - yarn run test-ci
after_success:
  - yarn run coveralls-ci
cache:
  yarn: true
  directories:
    - node_modules
